INHERIT: agda-pages/agda-pages.yml

site_name: Agda-Pages Demo
site_url:  https://pdmosses.github.io/agda-pages-demo/
repo_name: agda-pages-demo
repo_url:  https://github.com/pdmosses/agda-pages-demo

# To deploy website versions:
# - install mike (https://github.com/jimporter/mike/)
# - uncomment the following lines:
# extra:
#   version:
#     provider: mike

# The default list of theme features is inherited.
# For a custom list of features, override the inherited list:
# - append a copy of the default list from agda-pages/agda-pages-features.yml;
# - add and/or remove features from the list.
